shell:
  program: /bin/bash
  args:
    - --login

window:
        dynamic_padding: true
        decorations: full
        startup_mode: Maximized
font:
        normal:
                family: "Fira Code Nerd Font Mono" 
        bold:
                family: "Fira Code Nerd Font Mono"
        italic: 
                family: "Fira Code Nerd Font Mono"
        size: 10.0

custom_cursor_colors: true

colors:
  primary:
    background: '0x191919'
    foreground: '0xeaeaea'

  cursor:
    text:   '0xf1c1c1'
    cursor: '0xff2600'
